# Generated by Django 4.1.7 on 2023-06-02 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_alter_year_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coding', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comminication', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('coding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coding')),
                ('comminication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comunication')),
                ('theory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.theory')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
