# Generated by Django 4.1.7 on 2023-06-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_studentrating_cname_alter_studentrating_coding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='Name',
            field=models.CharField(default='maha', max_length=50),
        ),
    ]
